### ISSUE TITLE
Authorization Problems with remote Hoodie

### ISSUE THREAD

**Issue by rogeriochaves** [hoodiehq/hoodie#493] opened 2016-05-24 13:04 UTC
Hello, I have hoodie running in a separate project, there, my package.json just have one thing:

``` json
"dependencies": {
  "hoodie": "^22.0.4"
}
```

(i've also tried "git://github.com/hoodiehq/hoodie#tent", same issues)
Then I start it like this (I need to control all the ports and url because later I deploy this to heroku)

```
node_modules/hoodie/bin/start.js --admin-password 123 --port 4000 --db-url http://admin:123@127.0.0.1:5984 --bind-address localhost
```

I get "🐶  Your Hoodie app has started on http://localhost:4000", okay, no problems here. (I've also tried changing localhost to 0.0.0.0 or 127.0.0.1, no luck)

For using, I add the hoodie script on my other project like this:

```
<script type="text/javascript" src="//localhost:4000/hoodie/client.js"></script>
```

And create the hoodie singleton like this (hoodie.js):

``` javascript
const hoodie = new Hoodie({url: 'http://localhost:4000'});
export default hoodie;
```

Which I import on the other files to do stuff.

But when I try to sign up for example, by using this:

``` javascript
hoodie.account.signUp({username, password})
    .then(...)
    .catch(...);
```

Those requests are made (copying from chrome and skipping the OPTIONS ones):

**1 - account**

> curl 'http://localhost:4000/hoodie/account/api/session/account' -X PUT -H 'Origin: http://localhost:8000' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4,zh;q=0.2,gl;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2597.0 Safari/537.36' -H 'content-type: application/vnd.api+json' -H 'accept: application/vnd.api+json' -H 'Referer: http://localhost:8000/' -H 'Connection: keep-alive' --data-binary '{"data":{"type":"account","attributes":{"username":"3","password":"123"},"id":"hwn2p6q"}}' --compressed

_Response_

> 201 Created
> {"data":{"type":"account","attributes":{"username":"3","password":"123"},"id":"hwn2p6q"}}

**2 - session**

> curl 'http://localhost:4000/hoodie/account/api/session' -X PUT -H 'Origin: http://localhost:8000' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4,zh;q=0.2,gl;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2597.0 Safari/537.36' -H 'content-type: application/vnd.api+json' -H 'accept: application/vnd.api+json' -H 'Referer: http://localhost:8000/' -H 'Connection: keep-alive' --data-binary '{"data":{"type":"session","attributes":{"username":"3","password":"123"}}}' --compressed

_Response_

> 201 created
> {"links":{"self":"http://0.0.0.0:4000/session"},"data":{"id":"Mzo1NzU2QzJEMjo3KCIbT3ywciSszguYH4TA5oKSaw","type":"session","relationships":{"account":{"links":{"related":"http://0.0.0.0:4000/session/account"},"data":{"id":"hwn2p6q","type":"account"}}}},"included":[{"id":"hwn2p6q","type":"account","attributes":{"username":"3","roles":[]},"relationships":{"profile":{"links":{"related":"http://0.0.0.0:4000/session/account/profile"},"data":{"id":"hwn2p6q-profile","type":"profile"}}}}],"meta":{"id":"1464094162685:rchaves-MacBook-Air.local:59312:iolfupsk:10004"}}

**3 - user**

> curl 'http://localhost:4000/hoodie/store/api/user%2Fhwn2p6q/' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: http://localhost:8000' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4,zh;q=0.2,gl;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2597.0 Safari/537.36' -H 'Accept: _/_' -H 'Referer: http://localhost:8000/' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: accept, authorization' --compressed

_Response_

> 401 Unauthorized

Then it keeps repeating the last request, with JS throwing

```
XMLHttpRequest cannot load http://localhost:4000/hoodie/store/api/user%2Fxy3hyvb/. Response for preflight has invalid HTTP status code 401
```

This also happens after sign in, and hoodie shows nothing on its logs, even running with the `--verbose` option.

Is this a CORS issue? What should I do? This setup used to work on very old hoodie versions (pre pouchdb)

**Comment by gr2m** [comment] 2016-05-24 13:53
> git://github.com/hoodiehq/hoodie#tent

have you seen this floating around somewhre? It’s out of date, don’t use it any more :)

I think you’ve hit an issue that I’ve seen before myself, I thought we fixed it. After the sign in you see 401s when the replication of your local store gets started. Does reloading the page resolve the issue? It’s definitely not a CORS issue

**Comment by rogeriochaves** [comment] 2016-05-24 13:58
No, it doesn't solve the issue :T

**Comment by gr2m** [comment] 2016-05-24 17:25
can you reproduce the issue on https://tracker.hood.ie/ (run code in console)

**Comment by rogeriochaves** [comment] 2016-05-25 01:35
yes! Run this in the console:

``` javascript
const foo = new Hoodie({url: 'https://tracker.hood.ie:443'});
foo.account.signIn({username: 'foobar', password: '123'})
```

Sorry, this issue doesn't happen after sign up, it is after login, I forgot my code was signing in right after sign up.

**Comment by gr2m** [comment] 2016-05-25 14:47
Yes I can confirm that, but when you reload the page, the syncing works, right?

**Comment by rogeriochaves** [comment] 2016-05-25 16:45
yeah, you are correct, I'll try to understand why mine still have issues when reloading and come back here

**Comment by rogeriochaves** [comment] 2016-05-26 12:12
@gr2m okay, the easiest way to reproduce this is to use on another domain or port, so I made a jsbin, take a look:
http://jsbin.com/nisovanali/edit?html,js,output

**Comment by jameswestnz** [comment] 2016-05-27 04:57
I'm getting this issue now too.... Had been doing all dev to date as part of the hoodie app, and now I'm going onto our remote app and seeing this...

I may have a range of issues, not sure if they're related. Keen to see if you guys have notice something similar, and if it's related?
1. On initial login, hoodie is trying to sync with the incorrect user DB. I can see the browser using a different ID than the current user. On refresh, all as expected;
2. I'm not getting any syncing after refresh... Looking at the console I thought it may be related to the preflight failing (same as above), but sounds like it's not the case?
3. I can't logout because there is data still awaiting a sync... getting "CustomPouchError"

**Comment by jameswestnz** [comment] 2016-05-27 06:59
So it seems my issues have been compounded by attempting to run hoodie in an angular2/typescript/webpack environment... Problems still persist and I will be debugging further later, but hoping it's a bit easier this time ;)

**Comment by jameswestnz** [comment] 2016-05-28 03:42
@gr2m: any reason we're not using https://github.com/gr2m/hapi-cors-headers in Hoodie? I've just added it to my plugin, tweaked @hoodie/store-server slightly, and now everything is running as expected - errors gone, syncing working, logging out works great. That's also all running through the webpack/angular2 environment.

I'm going to submit a PR so we can review - keen to see if it works for others.

**Comment by gr2m** [comment] 2016-06-05 20:37
is this resolved via  https://github.com/hoodiehq/hoodie-store-server/issues/41 and https://github.com/hoodiehq/hoodie/issues/498?

**Comment by rogeriochaves** [comment] 2016-06-07 01:48
@gr2m Apparently cors issue is solved, but the problem you talked about before still happens:

> After the sign in you see 401s when the replication of your local store gets started. Does reloading the page resolve the issue?

Reloading does fix this, but I think we should close this issue and open another one for that

**Comment by gr2m** [comment] 2016-06-07 02:02
> Reloading does fix this, but I think we should close this issue and open another one for that

yes I agree. Create a follow up issue here: https://github.com/hoodiehq/hoodie/issues/503

**Closed as completed by gr2m** 2016-06-07 02:02 UTC

**Comment by gr2m** [comment] 2016-07-19 20:48
fyi the 401s after signin have been fixed via https://github.com/hoodiehq/hoodie-account-client/pull/103
