### ISSUE TITLE
Hoodie App Tracker - 401 Unauthorized from client.js - signout and edit email error 

### ISSUE THREAD

**Issue by Sticksword** [hoodiehq/hoodie#621] opened 2016-10-29 19:40 UTC
I did a fresh install via `git clone https://github.com/hoodiehq/hoodie-app-tracker.git` and then `npm install`. I am running via `npm start` and it shows me the cute little dog, which I'm assuming means all systems are green. Adding items is fine and I can create an account fine. However when I sign out or edit my email, I get a 401 error. I attached the screenshots. I have a hunch the client is not sending an Authorization header.

![screen shot 2016-10-29 at 12 25 18 pm](https://cloud.githubusercontent.com/assets/3814531/19832283/96dce178-9dd4-11e6-8fc4-39e6403b9fd2.png)

![screen shot 2016-10-29 at 12 24 38 pm](https://cloud.githubusercontent.com/assets/3814531/19832285/996c7aa2-9dd4-11e6-92b4-7cc980fb4770.png)

Details:
- I have not installed CouchDB and I don't have a PouchDB backend. I think the username and password info gets created within browser. I don't see how that could be a problem but I'm noting it here.
- I am using node v6.8.1 and npm v3.10.8 and I am on Mac OS X: El Capitan. 
- Results from `npm ls | grep hoodie`

```
Lean-Mean-Machine:hoodie-app-tracker michael$ npm ls | grep hoodie
hoodie-app-tracker@ /Users/michael/JSProjects/hoodie/hoodie-app-tracker
├─┬ hoodie@24.3.0
│ ├─┬ @hoodie/account@2.0.1
│ │ ├── @hoodie/account-client@4.4.0
│ │ └─┬ @hoodie/account-server@4.0.5
│ ├─┬ @hoodie/admin@1.2.2
│ ├─┬ @hoodie/client@5.0.7
│ │ ├── @hoodie/account-client@2.8.0
│ │ ├─┬ @hoodie/connection-status@3.0.0
│ │ ├── @hoodie/log@2.1.0
│ │ ├─┬ @hoodie/store-client@1.0.0
│ │ │ ├── hoodie-zuul-config@2.0.0
│ │ │ ├─┬ pouchdb-hoodie-api@1.6.4
│ │ │ └── pouchdb-hoodie-sync@1.4.1
│ ├─┬ @hoodie/server@21.1.1
│ │ ├─┬ @hoodie/store-server@2.1.5
│ ├─┬ @hoodie/store@1.0.4
│ │ └─┬ @hoodie/store-client@5.0.12
```

**Comment by gr2m** [comment] 2016-10-30 01:46
> I am running via npm start and it shows me the cute little dog

at what point does it show you the dog? We call it [Low-Profile dog](http://hood.ie/animals/#low-profile-dog) btw :)

**Comment by gr2m** [comment] 2016-10-30 01:47
I was able to reproduce the error, I’m looking into it 👍

**Comment by gr2m** [comment] 2016-10-30 03:41
`hoodie-client` did not have the latest dependencies, which was resolved via https://github.com/hoodiehq/hoodie-client/pull/98, but I still see problems with username change, I keep looking into it

**Comment by gr2m** [comment] 2016-10-30 18:56
I think I narrowed down the underlying problem. When we change a user’s username or password, they session gets invalidated due to the way sessions are currently implemented. The response to the `PATCH /account` request has a header that looks like `x-set-session:Z3JlZ29yQG1hcnR5bnVzLm5ldDo1ODI3RUI2NjoygYS7zi3IczmfUp55TsjThhxU5w`, but the account client does not use the session ID for further requests, instead it continues to use the old session id in request authorization header.

I'm pretty sure this needs to be fixed in the implementation of `hoodie.account.update`

**Comment by Sticksword** [comment] 2016-10-30 21:01
I see the Low-Profile dog after `hoodie` is run. The dog is followed by "Your Hoodie app has started".

Oh I see. That would make sense..

**Comment by gr2m** [comment] 2016-10-30 21:29
> I see the Low-Profile dog after hoodie is run. The dog is followed by "Your Hoodie app has started".

But that shouldn’t be, I wonder where you see it, it sounds like a bug. You should see the tracker app like on http://tracker.hood.ie?

**Comment by gr2m** [comment] 2016-10-30 21:34
@Sticksword can you run `npm update`? You should get `@hoodie/account-client@4.4.0` and `@hoodie/account-server@6.0.4`, check with `npm ls | grep hoodie`, here is mine:

```
├─┬ hoodie@24.3.1
│ ├─┬ @hoodie/account@2.0.1
│ │ ├── @hoodie/account-client@4.4.0
│ │ └─┬ @hoodie/account-server@4.0.5
│ ├─┬ @hoodie/admin@1.2.2
│ ├─┬ @hoodie/client@6.0.0
│ │ ├─┬ @hoodie/connection-status@3.0.0
│ │ ├── @hoodie/log@2.1.0
│ │ ├─┬ @hoodie/store-client@5.0.12
│ │ │ ├── hoodie-zuul-config@2.0.0
│ │ │ ├─┬ pouchdb-hoodie-api@1.6.4
│ │ │ └── pouchdb-hoodie-sync@1.4.1
│ ├─┬ @hoodie/server@21.1.2
│ │ ├─┬ @hoodie/account-server@6.0.4
│ │ │ └─┬ @hoodie/account-server-api@3.2.0
│ │ ├─┬ @hoodie/store-server@2.1.5
│ ├── @hoodie/store@1.0.4
```

The UI does not get updated, but changing username and password works now for me and does not cause `401`s

**Comment by gr2m** [comment] 2016-10-30 21:59
see https://github.com/hoodiehq/hoodie-app-tracker/pull/113.

Changing password now works correctly, but changing username does not, I’m looking into it. After username update the client sends the right header when sending further requests to both `/hoodie/account/api` and `/hoodie/store/api`. The ones to `/hoodie/account/api` go trough, but the ones to `/hoodie/store/api` fail with 401, so it most likely is an error with the server-side session validation

**Comment by gr2m** [comment] 2016-10-30 22:38
Okay, problem is that changing a username is technically deleting the users’s current document in CouchDB and creating a new one, as the username is part of the document ID. This is smart because it assures uniqueness of usernames. 

The bug is that [hoodie-account-server-api](https://github.com/hoodiehq/hoodie-account-server-api) still emits a `remove` event which makes [hoodie-server destroy that database](https://github.com/hoodiehq/hoodie-server/blob/master/index.js#L35-L43)

So we gotta fix this in `hoodie-account-server-api`, I’m on it

**Comment by gr2m** [comment] 2016-10-30 23:40
okay with https://github.com/hoodiehq/hoodie-account-server-api/releases/tag/v3.2.1 this should all work now. Can you check please?

To be that you have the latest version of everything, run `rm -rf node_modules && npm install`. Make sure you have 
- `@hoodie/account-client@4.4.0`
- `@hoodie/account-server@6.0.4`
- `@hoodie/account-server-api@3.2.1`

Thanks for your help, you found some major bugs in Hoodie 👍

**Comment by Sticksword** [comment] 2016-11-01 08:53
@gr2m not a problem! I did a fresh `npm install` and everything seems fine. I'll continue to poke around and eventually contribute, code-wise, to Hoodie :)

**Closed as completed** 2016-11-01 08:53 UTC

**Comment by gr2m** [comment] 2016-11-01 22:01
thanks for checking Michael!
